name: easy_turn
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+1
  firebase_auth: ^0.11.0
  cloud_firestore: ^0.11.0+1
  firebase_storage: ^3.0.0
  firebase_messaging: ^5.0.1+1
  shared_preferences: any
  carousel_pro: ^1.0.0
  carousel_slider: ^1.4.1
  url_launcher: ^5.4.2
  chewie: ^0.9.8+1
  intl: ^0.16.1
  flutter_datetime_picker: ^1.3.5
  font_awesome_flutter: ^8.7.0


 





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: "^0.5.0"
  path_provider: "^0.5.0+1"
  image: "^2.0.7"
  auto_size_text: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  http: any

  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/et-logo.png
    - assets/images/et-logo1.png
    - assets/images/usbapp-logo.png
    - assets/images/usbapp-logo1.png
    - assets/carousel/b1.jpg
    - assets/carousel/b2.jpg
    - assets/carousel/b3.jpg
    - assets/carousel/b4.jpg
    - assets/carousel/b5.jpg
    - assets/carousel/b6.jpg
    - assets/carousel/b7.jpg
    - assets/carousel/b8.jpg
    - assets/videos/usb.mp4


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Questrial
      fonts:
        - asset: fonts/Questrial-Regular.ttf
    - family: FugazOne
      fonts:
         - asset: fonts/FugazOne-Regular.ttf
         - weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
